*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZTESTDEPARTMENTU01.
                    "TABLEFRAME_ZTESTDEPARTMENT
INCLUDE LZTESTDEPARTMENTU02.
                    "TABLEPROC_ZTESTDEPARTMENT