*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY               **
*   NEVER CHANGE IT MANUALLY, PLEASE!                            **
*******************************************************************
FORM Z_MITI_DOWNLOAD %_RFC.
* Parameter declaration
DATA P_AREA TYPE
DD02L-TABNAME
.
DATA P_LOCAL_PATH TYPE
STRING
.
DATA P_LANGUAGE TYPE
L001TAB-DATA
.
DATA ROWSKIPS TYPE
SO_INT
.
DATA ROWCOUNT TYPE
SO_INT
.
DATA BEGIN OF EXPORT_TABLE OCCURS 10.
INCLUDE STRUCTURE
TAB512.
DATA END OF EXPORT_TABLE
.
* Assign default values
  P_LANGUAGE = 'E' .
  ROWSKIPS = 0 .
  ROWCOUNT = 0 .
* Call remote function
  CALL FUNCTION 'Z_MITI_DOWNLOAD' %_RFC
     EXPORTING
       P_AREA = P_AREA
       P_LOCAL_PATH = P_LOCAL_PATH
       P_LANGUAGE = P_LANGUAGE
       ROWSKIPS = ROWSKIPS
       ROWCOUNT = ROWCOUNT
     TABLES
       EXPORT_TABLE = EXPORT_TABLE
  .
ENDFORM.