*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZWYHOURLYU01.
                    "TABLEFRAME_ZWYHOURLY
INCLUDE LZWYHOURLYU02.
                    "TABLEPROC_ZWYHOURLY