*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZWYEMPU01.
                    "TABLEFRAME_ZWYEMP
INCLUDE LZWYEMPU02.
                    "TABLEPROC_ZWYEMP