PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZTESTEMPLOYEE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZTESTEMPLOYEE-ID .
    FIELD ZTESTEMPLOYEE-DEPARTMENTID .
    FIELD ZTESTEMPLOYEE-FIRST_NAME .
    FIELD ZTESTEMPLOYEE-SECOND_NAME .
    FIELD ZTESTEMPLOYEE-AGE .
    FIELD ZTESTEMPLOYEE-PLACE .
    FIELD ZTESTEMPLOYEE-PHONE_NUMBER .
    FIELD ZTESTEMPLOYEE-PINCODE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZTESTEMPLOYEE-ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.