*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZTESTEMPLOYEEU01.
                    "TABLEFRAME_ZTESTEMPLOYEE
INCLUDE LZTESTEMPLOYEEU02.
                    "TABLEPROC_ZTESTEMPLOYEE