*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZWYHEALTHU01.
                    "TABLEFRAME_ZWYHEALTH
INCLUDE LZWYHEALTHU02.
                    "TABLEPROC_ZWYHEALTH